version: 2
jobs:
  site-build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build site
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: dist
  site-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@pauloverde.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "26:7d:7c:ce:12:32:31:db:83:b9:66:a1:32:ca:15:e7"
      - run:
          name: Deploy site to gh-pages branch
          command: gh-pages --message "[skip ci] Updates" --dist dist
workflows:
  version: 2
  build:
    jobs:
      - site-build
      - site-deploy:
          requires:
            - site-build
          filters:
            branches:
              only: master
