version: 2
jobs:
  site-build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build site
          command: npm run build
      - persist_to_workspace:
          root: .
          paths: dist
  site-deploy:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Install and configure dependencies
          command: |
            npm install
            git config user.email "ci-build@pauloverde.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "52:d4:28:02:3f:c3:ac:c5:ea:0c:01:44:b8:fa:bc:69"
      - run:
          name: Deploy site
          command: npm run deploy
workflows:
  version: 2
  build:
    jobs:
      - site-build
      - site-deploy:
          requires:
            - site-build
          filters:
            branches:
              only: master
